# Generated by Django 5.0 on 2024-04-02 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faq",
            old_name="image",
            new_name="communication_tips",
        ),
    ]
